name: hng_2_task
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  extended_image: ^9.1.0
  fpdart: ^1.1.1
  flutter_bloc: ^9.0.0
  provider: ^6.1.2
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/image/

  fonts:
    - family: Axiforma
      fonts:
        - asset: assets/fonts/Axiforma-Thin.ttf
          weight: 100
        - asset: assets/fonts/Axiforma-Light.ttf
          weight: 300
        - asset: assets/fonts/Axiforma-Book.ttf
          weight: 400
        - asset: assets/fonts/Axiforma-Regular.ttf
          weight: 400
        - asset: assets/fonts/Axiforma-Medium.ttf
          weight: 500
        - asset: assets/fonts/Axiforma-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Axiforma-Bold.ttf
          weight: 700
        - asset: assets/fonts/Axiforma-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Axiforma-Heavy.ttf
          weight: 900

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
